---
# Example stack for deployment on our local usvc stack. Will spin up the tool in
# loop mode.
#
# The Google service account JSON encoded credentials must be present in a
# docker secret called "winter-pool-credentials" and the jobspec is in a config
# called "winter-pool-jobspec-example" The jobspec should include the following:
#
#   incoming_folder_id: "some folder id"
#   processed_folder_id: "some folder id"
#   credentials_path: "/credentials.json"
#
version: '3.5'

networks:
  traefik:
    name: traefik-net
    external: true

configs:
  jobspec:
    name: winter-pool-jobspec-exampl
    external: true

secrets:
  credentials:
    external: true
    name: winter-pool-credentials

services:
  tool:
    image: rjw57/winterpool-experiment
    command: [
      "--spec=/jobspec.yaml",
      "--loop",
      "--loop-sleep=600"
    ]
    deploy:
      replicas: 2
    configs:
      - source: jobspec
        target: /jobspec.yaml
    secrets:
      - source: credentials
        target: /credentials.json
    networks:
      - traefik
